### ISSUE TITLE
Servers Down?

### ISSUE THREAD

**Issue by MoHayat** [eyeseast/propublica-congress#33]
hello! I have been getting constant CongressErrors for a couple of days now everytime I run my code, any news on how long the servers are going to be down for?

**Comment by MoHayat** [comment]
UPDATE: it looks like only the bills under the 'major' category return errors, while others seem to be working fine.

**Comment by eyeseast** [comment]
Hi. I'm not affiliated with ProPublica and can't speak to their servers. You might check here: https://github.com/propublica/congress-api-docs
